"""
    Learning Unit Enrollment Service

    A set of API endpoints that allow you to get information about learning unit enrollment  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_enrollment_sdk
from osis_learning_unit_enrollment_sdk.model.subtype_enum import SubtypeEnum
from osis_learning_unit_enrollment_sdk.model.type_peps_enum import TypePepsEnum
globals()['SubtypeEnum'] = SubtypeEnum
globals()['TypePepsEnum'] = TypePepsEnum
from osis_learning_unit_enrollment_sdk.model.student_specific_profile import StudentSpecificProfile


class TestStudentSpecificProfile(unittest.TestCase):
    """StudentSpecificProfile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudentSpecificProfile(self):
        """Test StudentSpecificProfile"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudentSpecificProfile()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
