"""
    Learning Unit Enrollment Service

    A set of API endpoints that allow you to get information about learning unit enrollment  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_enrollment_sdk
from osis_learning_unit_enrollment_sdk.model.disability_subtype_peps_enum import DisabilitySubtypePepsEnum
from osis_learning_unit_enrollment_sdk.model.sport_subtype_peps_enum import SportSubtypePepsEnum
from osis_learning_unit_enrollment_sdk.model.type_peps_enum import TypePepsEnum
globals()['DisabilitySubtypePepsEnum'] = DisabilitySubtypePepsEnum
globals()['SportSubtypePepsEnum'] = SportSubtypePepsEnum
globals()['TypePepsEnum'] = TypePepsEnum
from osis_learning_unit_enrollment_sdk.model.enrollment_list import EnrollmentList


class TestEnrollmentList(unittest.TestCase):
    """EnrollmentList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEnrollmentList(self):
        """Test EnrollmentList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EnrollmentList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
