"""
    Learning Unit Enrollment Service

    A set of API endpoints that allow you to get information about learning unit enrollment  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_enrollment_sdk
from osis_learning_unit_enrollment_sdk.model.enrollment import Enrollment
from osis_learning_unit_enrollment_sdk.model.paginated_enrollment_list_all_of import PaginatedEnrollmentListAllOf
from osis_learning_unit_enrollment_sdk.model.paging import Paging
globals()['Enrollment'] = Enrollment
globals()['PaginatedEnrollmentListAllOf'] = PaginatedEnrollmentListAllOf
globals()['Paging'] = Paging
from osis_learning_unit_enrollment_sdk.model.paginated_enrollment_list import PaginatedEnrollmentList


class TestPaginatedEnrollmentList(unittest.TestCase):
    """PaginatedEnrollmentList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedEnrollmentList(self):
        """Test PaginatedEnrollmentList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedEnrollmentList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
