"""
    Learning Unit Enrollment Service

    A set of API endpoints that allow you to get information about learning unit enrollment  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_enrollment_sdk
from osis_learning_unit_enrollment_sdk.model.subtype_enum import SubtypeEnum


class TestSubtypeEnum(unittest.TestCase):
    """SubtypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubtypeEnum(self):
        """Test SubtypeEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SubtypeEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
