"""
    Learning Unit Enrollment Service

    A set of API endpoints that allow you to get information about learning unit enrollment  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_learning_unit_enrollment_sdk
from osis_learning_unit_enrollment_sdk.model.sport_subtype_peps_enum import SportSubtypePepsEnum


class TestSportSubtypePepsEnum(unittest.TestCase):
    """SportSubtypePepsEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSportSubtypePepsEnum(self):
        """Test SportSubtypePepsEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SportSubtypePepsEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
