# flake8: noqa

"""
    Learning Unit Enrollment Service

    A set of API endpoints that allow you to get information about learning unit enrollment  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.0.0"

# import ApiClient
from osis_learning_unit_enrollment_sdk.api_client import ApiClient

# import Configuration
from osis_learning_unit_enrollment_sdk.configuration import Configuration

# import exceptions
from osis_learning_unit_enrollment_sdk.exceptions import OpenApiException
from osis_learning_unit_enrollment_sdk.exceptions import ApiAttributeError
from osis_learning_unit_enrollment_sdk.exceptions import ApiTypeError
from osis_learning_unit_enrollment_sdk.exceptions import ApiValueError
from osis_learning_unit_enrollment_sdk.exceptions import ApiKeyError
from osis_learning_unit_enrollment_sdk.exceptions import ApiException
